// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPQkiM9NtT9UiCLhKf58mTwrId7MZ7VJs',
    appId: '1:199722517904:web:7086536586138960ca1f15',
    messagingSenderId: '199722517904',
    projectId: 'eventmate-e729a',
    authDomain: 'eventmate-e729a.firebaseapp.com',
    storageBucket: 'eventmate-e729a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARkq1CrQxV80I2BvzXHzFpeC3ZZngsqoA',
    appId: '1:199722517904:android:4508da270da4a719ca1f15',
    messagingSenderId: '199722517904',
    projectId: 'eventmate-e729a',
    storageBucket: 'eventmate-e729a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM_bXvCPkWQYKnR2mEPpG460zABFD-F8w',
    appId: '1:199722517904:ios:61b22d2963f54cc1ca1f15',
    messagingSenderId: '199722517904',
    projectId: 'eventmate-e729a',
    storageBucket: 'eventmate-e729a.firebasestorage.app',
    iosBundleId: 'com.example.eventmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM_bXvCPkWQYKnR2mEPpG460zABFD-F8w',
    appId: '1:199722517904:ios:61b22d2963f54cc1ca1f15',
    messagingSenderId: '199722517904',
    projectId: 'eventmate-e729a',
    storageBucket: 'eventmate-e729a.firebasestorage.app',
    iosBundleId: 'com.example.eventmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPQkiM9NtT9UiCLhKf58mTwrId7MZ7VJs',
    appId: '1:199722517904:web:46b1a5b1b7ad0cd8ca1f15',
    messagingSenderId: '199722517904',
    projectId: 'eventmate-e729a',
    authDomain: 'eventmate-e729a.firebaseapp.com',
    storageBucket: 'eventmate-e729a.firebasestorage.app',
  );
}
